### ISSUE TITLE
New code for web LAN

### ISSUE THREAD

**Issue by LawaxLawax** [seravifer/led-controller-desktop#2]
First, can you give me the time to explain my request to you it's totally possible I think of using it on the web knowing that you have developed it in electron and that js is executed if you don't want to help say it

**Comment by seravifer** [comment]
Please explain in detail what exactly you want, I don't understand.

**Comment by LawaxLawax** [comment]
What would be good would be to have a web interface to control the LED even locally, the local is enough because after that you just have to connect to an apache server to access the site so there is no worry.

So it would be nice to rewrite the code in the script in HTML format with simple buttons say that will execute javascript as simple as that.

I would have done it well and shared it but I can't read the code
