### ISSUE TITLE
Update ON/OFF Button when hitting a Color

### ISSUE THREAD

**Issue by ambozz** [seravifer/led-controller-desktop#4]
When the Device is Turned off and someone clicks a Color it turns on as it should, but the Button to enable/disable the device doesn't update.

And since we can control the Devices with for example our phones it would be nice to have the Color & ON/OFF Button Updated every time the Window Opens (Doesn't need to do this live, one time when the window opens is enough, since after that it is controlled from it and not something else)

Edit:
But anyway thanks for the nice Tool <3

**Comment by seravifer** [comment]
Done 😃. Released on 1.1.0
