### ISSUE TITLE
How do I install - Deploy in Device

### ISSUE THREAD

**Issue by jefersonlleite** [seravifer/led-controller-desktop#5]
Hi
how do I build the installation package and deploy to the device?

Best regards

**Comment by seravifer** [comment]
I can't understand you. Can you explain in more detail what you need?

You do not need to install anything, it is a portable program for Windows.

**Comment by jefersonlleite** [comment]
Hello servicer,
thank very much for the feedback.
so, I need to install a interface on a mobile device (android and / or IoS)
it's possible?

**Comment by jefersonlleite** [comment]
The application needs execute by mobile device and not by desktop windows, 
Do you understand?

**Comment by jefersonlleite** [comment]
Hi Seravife, 
One more question , please..
Do you know anythink mobile application for to do this or tutorial , link ...whatrever
regards

**Comment by ambozz** [comment]
For mobile just use the official Magic Home App.
